### PR TITLE
Add ping event

### PR DESCRIPTION
**Pull request by valga**

### CODE REVIEW

**Comment by cboden** [comment]
What do you need access to the ping event for?

**Comment by valga** [comment]
To keep track of last received frame from a server.

I can already bind listener for `pong` and `message` events, so only thing missing is `ping` event.

**Comment by SteveJobzniak** [comment]
@cboden Knowing the last frame from a server can be very important when implementing other people's websocket protocols. So please accept this missing ping event! :) 👍

**Comment by mbonneau** [comment]
Not a fan of adding this event as these use cases should probably be handled differently, but I will merge as it does not add significantly to the API surface area and there appears to be enough interest.

**Comment by valga** [comment]
@mbonneau Just curious, but what would be the best option to detect dead connections with ease?

**Comment by mbonneau** [comment]
@valga Using pings is the correct way, but it should just be built into the library. This is how it is done in the Ratchet server: https://github.com/ratchetphp/Ratchet/blob/0d31f3a8ad4795fd48397712709e55cd07f51360/src/Ratchet/WebSocket/WsServer.php#L198.

**Pull request merged**
