### PR TITLE
Converts "wss" scheme into "https" scheme

### PR DESCRIPTION
**Pull request by claudiosdc**
Converts "wss" scheme into "https" scheme instead of always using "http" scheme and does not add unnecessary default ports when generating request.

### CODE REVIEW

**Comment by claudiosdc** [comment]
I was having a hard time connecting to a WebSocket service (Catenis notifications) and realized that it was due to the fact that the original WebSocket URI (wss://sandbox.catenis.io/..) was getting converted to an HTTP URI (http://sandbox.catenis.io:443/...) instead of to an HTTPS URI (https://sandbox.catenis.io/...) with no port appended to the host name.

Applying this fix solved the issue.

**Comment by clue** [comment]
@claudiosdc Thank you, I agree that this change makes sense! :+1: 

Can you add a test for this to ensure this actually returns the expected request (the scheme is case-insenstive by definition, but all uppercase still looks strange to me) and also to ensure this doesn't break again in the future? :+1:

**Comment by claudiosdc** [comment]
@clue Added corresponding unit test as per your request.

I hope you guys can generate an updated version of this package including this fix any time soon.

**Comment by mbonneau** [comment]
@claudiosdc Thanks for the update and the tests!

**Pull request merged**
