### PR TITLE
Added WebSocket close code

### PR DESCRIPTION
**Pull request by uniquoooo**

### CODE REVIEW

**Comment by uniquoooo** [comment]
Haven't tested this, don't know how to use the test suite.

**Comment by cboden** [comment]
Awesome @uniquoooo. My apologies for this, but I've just done a large push to master from the rfc pull request. Would you be able to rebase your PR against the latest master?

**Comment by uniquoooo** [comment]
Will do, looks good!

**Comment by uniquoooo** [comment]
Re-implemented the changes. Haven't tested it yet however.

**Comment by uniquoooo** [comment]
Should be working now.

Not sure if it's related to the lib but `$frame->getContents()` returns the contents with 2 extra bytes at the start, didn't happen on the old version.

**Comment by cboden** [comment]
`getContents` gets the raw contents of the Frame including the 2 byte header indicating things such as the opcode, mask indicator, and payload length. Instead of `getContents` you probably want to use `getPayload`.

**Comment by cboden** [comment]
Tested and merged. Thanks @uniquoooo! This uncovered an underlying behaviour in the RFC lib that I was not expecting (although, not technically a bug :smile:).

**Pull request merged**
