### PR TITLE
added example on period task

### PR DESCRIPTION
**Pull request by skecskes**
Hi, this solution, where I periodically send some message, ideally ping, fixed for me issue (https://github.com/ratchetphp/Pawl/issues/67) where websocket server disconnected me after 1 minute. May be worth adding this to examples

### CODE REVIEW

**Comment by mbonneau** [comment]
I think adding a periodic text message with the contents `ping` may be a little confusing for people considering the protocol supports pings using control frames.

**Comment by skecskes** [comment]
Yes, it might be confusing, but it keeps connection live. I wasn't able to send real ping. Maybe you could show us example how to do that using control frames?

**Comment by mbonneau** [comment]
@skecskes - I don't have a moment to check this right now, but I think the `send` method will accept an application-constructed `Frame` so you could send a websocket control frame ping like this:
```php
$conn->send(new Frame('', true, Frame::OP_PING));
```
This idea is another leaky abstraction thing though. The correct solution would be to add a keep-alive mechanism into the library itself.

**Comment by skecskes** [comment]
@mbonneau thank you for example, it works. Keep-alive stuff would definitely very helpful for many people. Ideally keep-alive would be defaultly turned off and optionally activated. Payload, frame type and period would need to be variable as there are many different implementations of what is keep-alive. 

Anyway, I achieved all I wanted, which is sending periodic messages. If you thing the pull request is more confusing than helpful, just reject it. Thanks for help.

**Pull request closed without merging**
